### PR TITLE
Enable CI on old versions of Julia

### PR DESCRIPTION
**Pull request by LilithHafner**

### CODE REVIEW

**Comment by tecosaur** [comment]
I think this is for the planned 1.0 support. However, since that requires more than just an `@static if VERSION < X include("compat.jl") end`, we'll need a 1.0 branch and this change will need to be applied there.

**Comment by tecosaur** [comment]
See https://github.com/julialang/StyledStrings.jl/tree/julia1-compat for the WIP attempt

**Comment by tecosaur** [comment]
Can we close this?

**Comment by LilithHafner** [comment]
If you're willing to accept the additional maintenance burden of having two branches to maintain instead of just one, then yes.

**Comment by tecosaur** [comment]
There are some pretty major changes required for compatibility with pre-1.11 versions of Julia, so I think it makes more sense to maintain a branch.

I'm thinking that around the Julia 1.11 release, we make a StyledStrings release from that branch (say `1.0`), then a release from `main` (`1.11`), and after that the branch is left as bugfix-only with future changes just going to `main`.

**Pull request closed without merging**
