### PR TITLE
Build docs in CI

### LINKED ISSUE #8: Bug in src/regioniterator.jl
https://github.com/JuliaLang/StyledStrings.jl/blob/74e7135ef86ef50a62f19956c7a5f824c391389e/src/regioniterator.jl#L30

`import AnnotatedString` does not make sense. I think this would get caught in CI if it built docs.

### PR DESCRIPTION
**Pull request by LilithHafner**
The two commits build everything and fail due to failed doctests due to #8 
The remaining commits should fix that failure, fix #8, make CI green, and unblock https://github.com/JuliaLang/julia/pull/51869

### CODE REVIEW

**Comment by LilithHafner** [comment]
CI failed for the right reasons!

**Comment by tecosaur** [comment]
Does anything more actually need to happen for this to be ready to merge?

**Comment by LilithHafner** [comment]
The commits in this PR reflect my actual development process. They are useful for me now in keeping track of what I've done and still need to do and making sense of CI results. There's no need to erase this history, but they should not make it into the main branch's history. I recommend merging this via "squash and merge".

Making documentation reasonably bug-free and checking that all the links work in all the context this documentation appears in is still a big todo, but this makes Docs build and CI green, and does not introduce much hackieness (aside from those hardcoded URLs from [9067fa1](https://github.com/JuliaLang/StyledStrings.jl/pull/19/commits/9067fa1159d9237a30a3b95d1033eeb0da22e23c)) so I think it's ready to go!

**Comment by tecosaur** [comment]
Thanks for doing this Lilith! I take it it's good to merge?

**Comment by tecosaur** [comment]
Update: actually read the last few words of your comment :sweat_smile:. Thanks again :slightly_smiling_face:

**Comment by tecosaur** [comment]
> does not introduce much hackieness (aside from those hardcoded URLs from [9067fa1](https://github.com/JuliaLang/StyledStrings.jl/pull/19/commits/9067fa1159d9237a30a3b95d1033eeb0da22e23c))

I'm thinking I might just copy the approach of https://github.com/JuliaLang/Distributed.jl/blob/master/docs/make.jl and set:

```julia
    checkdocs = :exports,
    warnonly = [:cross_references],
```

**Comment by tecosaur** [comment]
I've got a few tweaks I want to try, if they don't pan out I'll just revert to the current state.

**Comment by tecosaur** [comment]
I think this is a little better, let's give it a shot :)

**Comment by LilithHafner** [comment]
You deleted all the history and made multiple force pushes so I can no longer see my history nor get an ergonomic view of what you changed since my latest changes :(

**Comment by tecosaur** [comment]
Oh the history is still there, it's just detached :slightly_smiling_face: (and GitHub seems to be doing a worse-than-usual job showing it).

Here's a diff from the last commit you pushed to what I merged: https://github.com/JuliaLang/StyledStrings.jl/compare/090c05f92c3e7e..c49ae82f2b1765. Short rundown:
- More the CI task back into `CI.yml`
- Fix the manifest gitignore rule (your change made git pay attention to the root manifest)
- Condense the `docs/make.jl` statements (make use of the default values/autodetection more)
- Change the `@ref` approach from full URLs to `warnonly = [:cross_references]`
- Fix a typo in `internals.md`
- Sort the symbols documented in `internals.md`
- Pull changes to `main`

**Comment by tecosaur** [comment]
Also, looks like the inclusion of `Base.{parse,tryparge,merge}` here causes issues when building the Julia docs: https://buildkite.com/julialang/julia-master/builds/29596#018b8c30-3982-4a72-838c-a905a5c2d6d2

**Pull request merged**
