### PR TITLE
Add `\r` to the list of non-unescaped characters to fix windows CI

### PR DESCRIPTION
**Pull request by LilithHafner**

### CODE REVIEW

**Comment by LilithHafner** [comment]
Whelp, that fixed it. Manually listing many escape characters is typically codesmell. It is notoriously difficult to get escaping and unescaping right. @tecosaur, how do we know we've got the right set of characters to not unescape?

**Comment by tecosaur** [comment]
What I wonder with `\r` is whether we need to change the special handling with `\n` that allows for:
```julia
styled"some content \
       split across \
       lines"
```

(this is currently missing a test)

**Comment by LilithHafner** [comment]
> Well, each one of those was added for a particular reason.

IIUC `['{', '}', ':', '$']` is a complete list of the special characters used in the styled macro and therefore must receive special treatment here. That makes sense.

The presence of `\n` and `\r` is weird, though.

**Comment by tecosaur** [comment]
`\n` was added because I wasn't able to make the `\`-continued lines work without it.

**Comment by LilithHafner** [comment]
I was going to say "shouldn't you just use the built-in support for strings without newlines split across multiple lines?" but it seems that Julia does not have support for this 😢

**Comment by LilithHafner** [comment]
That's sad and error-prone. Julia should provide a way to reuse the existing string parsing machinery.

```
julia> "abc\
       def"
"abcdef"

julia> macro noop_str(str)
           println(str)
           str
       end
@noop_str (macro with 1 method)

julia> noop"abc\
       def"
abc\
def
"abc\\\ndef"
```

**Comment by LilithHafner** [comment]
It looks like Base strings identify and delete things that match the regex`\\(\r|\n)\S*` (i.e. backslack, followed by a newline or carriage return, and then any subsequent whitespace)

https://github.com/JuliaLang/JuliaSyntax.jl/blob/1b048aad2a3a3e2e9d7f5053ff51024f08ca308c/src/parser.jl#L3354-L3358

**Comment by tecosaur** [comment]
I thin we're just accomplishing the same effect via state machine instead of regexp.

**Comment by LilithHafner** [comment]
Oh, JuliaSyntax also doesn't use a Regex, that was just to state what's going on.

**Comment by LilithHafner** [comment]
Anyway, moving discussion to #16

**Comment by tecosaur** [comment]
I think this is superseded by #16 being merged.

**Pull request closed without merging**
