### PR TITLE
mark API Experimental

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by tecosaur** [comment]
This seems prudent to me at this stage given the discussion that's started up over the past month or two.

**Comment by topolarity** [comment]
I think this didn't end up rendering quite right: 
image

**Comment by tecosaur** [comment]
Ah yep, giving it a second look it needs some extra spaces. Thanks for catching this!

**Comment by tecosaur** [comment]
Should be corrected in af972e0a772069b4996cdd206d4e36defebd2453.

**Pull request merged**
